#!/usr/bin/python3
import os
import re
import time

currentTime = int(time.time())

print("<<<backuppc>>>")

path = '/var/lib/backuppc/pc/'
for pc in os.listdir(path):
    statusFile = open(path + pc + '/backups', 'r')
    for line in statusFile.readlines():
        m = re.search('^[0-9]+\t(incr|full)\t[0-9]+\t([0-9]+)\t[0-9]+\t([0-9]+)', line)
        if (m):
            last = m
            if (m[1] == 'full'):
                lastFull = m
    if lastFull:
        print("{} {} {} {}".format(pc, currentTime - int(last[2]), currentTime - int(lastFull[2]), lastFull[3]))
