#!/usr/bin/perl
use JSON::XS;

# read perl data from BackupPC
$code = `sudo -ubackuppc /usr/share/backuppc/bin/BackupPC_serverMesg status hosts`;

if($code =~ /^Got reply: (.*)$/) {
  $code = $1;
}
else {
  print "Does not match!\n";
  exit(1);
}

# convert to data structure
eval $code;

# print to JSON
print "<<<backuppc>>>\n";
foreach $key (keys %Status) {
  if ($key !~ /^ /) {
    $age = time() - $Status{$key}{'lastGoodBackupTime'};
    print "$key $age\n";
  }
}
